version: "3.7"
services:
  bck_node_mongo_clean:
    image: kathemica/bck_node_mongo_clean:latest
    hostname: node-backend
    container_name: node-backend
    restart: always
    volumes:
      - ./certs:/usr/app/certs
    environment:
      - SERVER_FINGERKEY= SET YOUR RAMDON FINGERKEY HERE
      - SENDGRID_API_KEY= SET YOUR API KEY HERE
      - JWT_SECRET= WRITE A RANDOM STRING HERE
      - CA_TOKEN_MONGO= WRITE YOUR CA.cert PASSWORD HERE
      - MONGO_URL= INSERT YOUR MONGO_URL HERE
      - MAIL_OWNER= NAME A MAIL_OWNER HERE
      - MAIL_USERNAME= SENDGRID USERNAME HERE
      - MAIL_FROM= SENDGRID MAIL FROM HERE
      - IS_TLS_MONGO= Should I connect with mongodb as TLS?
      - DB_NAME=INSERT YOUR DATABASE NAME HERE
      - isHTTPS=Will I to connect with HTTPS?
    ports:
      - 8051:8051
      - 443:443
    networks:
      - api_server_default
    command: node ./src/main/server/server.js
networks:
  api_server_default:
    driver: bridge
